version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependabot-updates"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dependabot-updates"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
